spring.application.name=diacono

#referenciar as chaves do security
jwt.public.key = classpath:testepublic.key
jwt.private.key = classpath:testeprivate.key

# habilita o corretor tratamento de erros de validacao nas respostas HTTP
server.error.include-binding-errors=always
server.error.include-message=always

spring.datasource.url=${DB_URL:jdbc:h2:mem:diacono}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=${DB_INIT_MODE:embedded}

# console do h2: http://localhost:8080/h2-console
spring.h2.console.enabled=${DB_ENABLED_H2:true}

spring.jpa.defer-datasource-initialization=${JPA_INITILIZATION:true}

#config spring security e oauth2
spring.config.import=optional:file:.env[.properties]
app.field.encryption.key=${APP_FIELD_ENCRYPTION_KEY:}
google.oauth.client-id=${GOOGLE_OAUTH_CLIENT_ID:}
google.oauth.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET:}
google.oauth.token-uri=${GOOGLE_OAUTH_TOKEN_URI:https://oauth2.googleapis.com/token}

#config rabbitmq
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASS:guest}

app.rabbit.exchange=diacono.exchange
app.rabbit.queue.evento-criado=diacono.evento.queue
app.rabbit.routing-key.evento-criado=diacono.evento.rk

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

spring.cache.type=redis
spring.cache.redis.time-to-live=3m
spring.cache.redis.cache-null-values=false
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=diacono: