spring.application.name=diacono

#referenciar as chaves do security
jwt.public.key = classpath:testepublic.key
jwt.private.key = classpath:testeprivate.key



# habilita o corretor tratamento de erros de validacao nas respostas HTTP
server.error.include-binding-errors=always
server.error.include-message=always

# para exibir os comandos SQL formatados no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# habilita o H2 console (nao e necessario ficar fazendo isso)
# console do h2: http://localhost:8080/h2-console
spring.h2.console.enabled=true

# indica a URL de acesso ao banco de dados (so compensa se habilitar o e quiser acessar o H2 console, senao nao precisa para o H2, so para outros bancos de dados - vide apostila -)

spring.datasource.url=jdbc:h2:mem:diacono
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=embedded

#config spring security e oauth2
spring.config.import=optional:file:.env[.properties]

#config rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.rabbit.exchange=diacono.exchange
app.rabbit.queue.evento-criado=diacono.evento.queue
app.rabbit.routing-key.evento-criado=diacono.evento.rk

